# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('instruction', models.TextField()),
                ('url', models.URLField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Gameplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('state', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy_type', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.Taxonomy')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=512)),
                ('bio', models.TextField()),
                ('register_date', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
                ('user_type', models.CharField(max_length=10)),
                ('is_validated', models.BooleanField()),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='gameapp.Asset')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.User'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.User'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.Game'),
        ),
        migrations.AddField(
            model_name='gameplay',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.User'),
        ),
        migrations.AddField(
            model_name='game_taxonomy',
            name='taxonomy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.Taxonomy'),
        ),
        migrations.AddField(
            model_name='game',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.User'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.User'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.Game'),
        ),
    ]
