# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='game_taxonomy',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='game_taxonomy',
            old_name='taxonomy_id',
            new_name='taxonomy',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='taxonomy',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_id',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='asset',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameapp.Game'),
        ),
        migrations.AddField(
            model_name='game',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gameplay',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.Asset'),
        ),
    ]
