# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0002_auto_20170203_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
