# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0003_auto_20170204_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplay',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='gameplay',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='game_id',
            new_name='game',
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
