# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0005_auto_20170205_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameapp.Asset'),
        ),
    ]
