# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0011_purchase_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplay',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gameplay',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
