# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0012_auto_20170210_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='state',
            new_name='status',
        ),
    ]
