# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0013_auto_20170210_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='games',
            field=models.ManyToManyField(to='gameapp.Game'),
        ),
    ]
