# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0014_taxonomy_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_taxonomy',
            name='game',
        ),
        migrations.RemoveField(
            model_name='game_taxonomy',
            name='taxonomy',
        ),
        migrations.DeleteModel(
            name='Game_Taxonomy',
        ),
    ]
