# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0015_auto_20170212_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_taxonomy',
            name='game',
        ),
        migrations.RemoveField(
            model_name='game_taxonomy',
            name='taxonomy',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='taxonomies',
            field=models.ManyToManyField(to='gameapp.Taxonomy'),
        ),
        migrations.DeleteModel(
            name='Game_Taxonomy',
        ),
    ]
